name: Sample App Tests

on: push

jobs:
    sample_app_tests:
        name: "Run Tests Using Jest"
        runs-on: ubuntu-latest
        permissions:
            id-token: write
            contents: read
        defaults:
            run:
                working-directory: sample-app-tut
        steps:
            - uses: actions/checkout@v6
            - run: npm install
            - run: npm test

            - uses: aws-actions/configure-aws-credentials@v3
              if: github.ref == 'refs/heads/main'
              with:
                role-to-assume: arn:aws:iam::157320905197:role/ex-ci-cd-permissions-20260615192332316600000001 #3 Assume the apply IAM role (main branch only).
                role-session-name: apply-${{ github.run_number }}-${{ github.actor }}
                aws-region: us-east-2
            
            - uses: opentofu/setup-opentofu@v1  #5

            - name: Tofu Test
              working-directory: ./tofu/live/ci-cd-permissions #7
              run: |
                tofu init -backend=false -input=false
                tofu test -verbose
            